/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/ui/button/Button.vue')['default']
    IPhCheckCircleFill: typeof import('~icons/ph/check-circle-fill')['default']
    IPhInfoFill: typeof import('~icons/ph/info-fill')['default']
    IPhMoon: typeof import('~icons/ph/moon')['default']
    IPhSpinnerGapBold: typeof import('~icons/ph/spinner-gap-bold')['default']
    IPhSun: typeof import('~icons/ph/sun')['default']
    IPhWarningCircleFill: typeof import('~icons/ph/warning-circle-fill')['default']
    IPhWarningFill: typeof import('~icons/ph/warning-fill')['default']
    IPhX: typeof import('~icons/ph/x')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VFoot: typeof import('./components/v-foot.vue')['default']
    VLayout: typeof import('./components/v-layout.vue')['default']
    VNav: typeof import('./components/v-nav.vue')['default']
    VToaster: typeof import('./components/v-toaster.vue')['default']
  }
}
